### ISSUE TITLE
Implement DataPackage class

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-js#11]
# Overview

```
async DataPackage(descriptor, profile='base', raise_invalid=True, remote_profiles=False)
    valid -> bool
    errors -> list
    descriptor -> dict
    update(**values)
    add_resource(descriptor)
    resources -> Resource[]
```

# Tasks

- [x] implement stub `DataPackage` class wich could be instantiated as `Promise`
- [x] add `constructor` method to store all arguments as internal state
  - [x] descriptor could be javascript object OR
  - [x] descriptor could be a link to json file (local or remote)
  - [x] call `validate(descriptor)` in constructor to validate datapackage descriptor
    - [x] if `raise_invalid` raise on invalid
    - [x] if not `raise_invalid` don't raise on invalid just store errors internally
- [x] implement `datapackage.valid` getter (always true if `raise_invalid` is true otherwise depends on validatation result)
- [x] implement `datapackage.errors` getter (always empty array if `raise_invalid` is true otherwise list of validation errors)
- [x] implement `descriptor` getter
- [x] implement `update` method 
  - [x] merge provided object to descriptor and re-validate (use `raise_invalid` logic here also)
  - [x] raise an error if user trying to alter `resources` key
- [x] implement `resources` getter returning array of earlier implemented `Resource` instances
- [x] implement `add_resource` method 
  - [x] should update descriptor
  - [x] should update resources
  - [x] should trigger datapackage revalidation (use `raise_invalid` logic here also)
- [ ] write comprehensive tests using `data` dir (real datapackage descriptors)

**Comment by dumyan** [comment]
@roll I'm curious about this

> implement datapackage.errors getter (always empty array if raise_invalid is true otherwise list of validation errors)

Why should we hide the errors on `raise_invalid`? I think it would be better to show the errors if the consumer asks for them, just not raising any errors and allowing working with a invalid datapackage will be enough I think for `raise_invalid`.

**Comment by roll** [comment]
@dumyan 
We don't need to hide if raise_invalid = true, constructor or mutator must throw validation error. It means it's not possible to reach state with both (raise_invalid and instance with errors).
