### ISSUE TITLE
Implement validate function

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-js#13]
# Overview

There should be a function to validate datapackage descriptor against datapackage profile schema:

```
async validate(descriptor, profile='base', remote_profiles=False) -> raise/true
```

It should raise list of errors. See - https://github.com/frictionlessdata/jsontableschema-js#validate

This function should encapsulate work with different datapackage profiles (register) - we should decide how based on `datapackage-py` experience. This function will be used inside `DataPackage` class.

# Tasks

- [x] finish https://github.com/frictionlessdata/datapackage-js/issues/14
- [x] see example - https://github.com/frictionlessdata/jsontableschema-js/blob/master/src/validate.js
- [x] consider using some validation code from - https://github.com/frictionlessdata/datapackage-validate-js
- [x] implement `validate` function (see API above)
- [ ] write comprehensive tests using `data` dir (real datapackage descriptors)
