### ISSUE TITLE
Put in order javascript libraries

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-js#22]
# Overview

We have many javascript libraries - https://github.com/frictionlessdata?language=javascript&q=&type=&utf8=%E2%9C%93

- some of them should be deprecated after `datapackage-js` will be ready (merged)
- not merged ones should be better described with some docs in readme

# Tasks

- [x] deprecate `datapackage-registry-js` (`datapackage.Profiles`)
- [x] deprecate `datapackage-validate-js` (`datapackage.validate`)
- [ ] `datapackage-identifier-js` - #21
- [ ] `datapackage-init-js` - #15 
- [ ] `datapackage-from-remote-js` - ?
- [ ] `datapackage-read-js` - ?
- [ ] `datapackage-outfile-js` - ?
- [ ] `datapackage-ckan-js` - ?
- [ ] `jsontableschema-openrefine-py` - ?

**Comment by roll** [comment]
MOVED
https://github.com/frictionlessdata/stack/issues/9
