### ISSUE TITLE
Add runnable usage examples

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-js#33]
# Overview

Use `examples` dir to add runnable example of the lib work.

# Tasks

- [ ] add `examples` dir
- [ ] add to examples to this dir
- [ ] ensure example code works
