### ISSUE TITLE
Release version-1

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-js#47]
# Overview

That's a tracking issue for the milestone https://github.com/frictionlessdata/datapackage-js/milestone/2

# Tasks

- [x] rebase on specs-v1
- [x] release ALPHA
---
- [x] make `await resource.table` sync (available in the latest `tableschema`)
- [x] validate single Resource (not only as a part of data package)
- [x] wait specs final release
- [ ] release
