### ISSUE TITLE
Setup repository for library update

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-js#5]
# Overview

Before work on actual code we should setup repository with CI/CD based on current practice.

# Tasks
- [x] read http://specs.frictionlessdata.io/
- [x] read https://github.com/frictionlessdata/project/issues/288
- [x] read https://github.com/frictionlessdata/project/issues/289 (for now `datapackage` reference is work in progress so here we will be working on it)
- [x] copy https://github.com/frictionlessdata/jsontableschema-js repository
- [x] remove everything related to actual code preserving just skeleton with travis, webpack etc
- [x] in readme add note about breaking changes from `v0.2` (see https://github.com/frictionlessdata/jsontableschema-js#json-table-schema), create skeleton bases on https://github.com/frictionlessdata/jsontableschema-py#json-table-schema readme structure, update badges (table of contents is not needed)
- [x] prepare PR to master, ping @roll
