### ISSUE TITLE
Ensure there is no path traversing vulnerabilities

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-js#50]
# Overview

There should be no way to access local paths outside of datapackage basedir.

# Tasks

- [ ] review current situation
- [ ] fix code if needed
- [ ] write comprehensive test to cover different attack vectors
